@RestauSimplon_HostAddress = https://localhost:7287

GET {{RestauSimplon_HostAddress}}/

###

GET {{RestauSimplon_HostAddress}}/articles

###
GET {{RestauSimplon_HostAddress}}/articles/disponible

###


POST {{RestauSimplon_HostAddress}}/articles
Content-Type: application/json

{
  "nom":"Pizza Margharita",
  "prix":11.50,
  "categorie":"plat",
  "description":"La plus simple et la plus élégante !",
  "disponible":true
}
###
GET {{RestauSimplon_HostAddress}}/clients

###

POST {{RestauSimplon_HostAddress}}/clients
Content-Type: application/json
{
  "nom":"Dupont",
  "prenom":"Jean",
  "numeroRue":"13",
  "nomRue":"Rue de la Paix",
  "ville":"Paris",
  "codePostal":75000,
  "telephone":"+33612345678"
}
###
