@RestauSimplon_HostAddress = https://localhost:7287

GET {{RestauSimplon_HostAddress}}/

###

GET {{RestauSimplon_HostAddress}}/articles

###
GET {{RestauSimplon_HostAddress}}/articles/disponible

###


POST {{RestauSimplon_HostAddress}}/articles
Content-Type: application/json

{
  "nom":"Pizza Margharita",
  "prix":11.50,
  "categorie":"plat",
  "description":"La plus simple et la plus élégante !",
  "disponible":true
}
###
GET {{RestauSimplon_HostAddress}}/clients

###

POST {{RestauSimplon_HostAddress}}/clients
Content-Type: application/json
{
  "nom":"Dumont",
  "prenom":"Jeanne",
  "numeroRue":"13B",
  "nomRue":"Rue de la Guerre",
  "ville":"Sirap",
  "codePostal":"57000",
  "telephone":"+33687654321"
}
###

@id=2
GET {{RestauSimplon_HostAddress}}/clients/{{id}}

###

DELETE {{RestauSimplon_HostAddress}}/clients/{{id}}

###

PUT {{RestauSimplon_HostAddress}}/clients/{{id}}
Content-Type: application/json
{
  "id":3,
  "nom":"Dupont",
  "prenom":"Jean",
  "numeroRue":"13A",
  "nomRue":"Rue de la Paix",
  "ville":"Paris",
  "codePostal":"75000",
  "telephone":"+3312345678"
}

###

POST {{RestauSimplon_HostAddress}}/commande-articles
Content-Type: application/json
{
  "idCommande":1,
  "idArticles":[1,2,3]
}
###

GET {{RestauSimplon_HostAddress}}/commandes

###

POST {{RestauSimplon_HostAddress}}/commandes
Content-Type: application/json
{
  "typeCommande":"livraison",
  "clientId":1
}
###

GET {{RestauSimplon_HostAddress}}/commandes/{{id}}

###

DELETE {{RestauSimplon_HostAddress}}/commandes/{{id}}/supprimer

###

PUT {{RestauSimplon_HostAddress}}/commandes/{{id}}/terminee
Content-Type: application/json
{
  "typeCommande":"surPlace",
  "clientId":1
}
###
