@RestauSimplon_HostAddress = https://localhost:7287

GET {{RestauSimplon_HostAddress}}/

###

GET {{RestauSimplon_HostAddress}}/articles

###
GET {{RestauSimplon_HostAddress}}/articles/disponible

###


POST {{RestauSimplon_HostAddress}}/articles
Content-Type: application/json

{
  "nom":"Pizza Margharita",
  "prix":11.50,
  "categorie":"plat",
  "description":"La plus simple et la plus élégante !",
  "disponible":true
}
###
GET {{RestauSimplon_HostAddress}}/clients

###

POST {{RestauSimplon_HostAddress}}/clients
Content-Type: application/json
{
  "nom":"Dumont",
  "prenom":"Jeanne",
  "numeroRue":"13B",
  "nomRue":"Rue de la Guerre",
  "ville":"Sirap",
  "codePostal":"57000",
  "telephone":"+33687654321"
}
###

@id=2
GET {{RestauSimplon_HostAddress}}/clients/{{id}}

###
